spring :
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 10000
            maximum-pool-size: 10
            minimum-idle: 15
            pool-name: HikariConnectionPool
      
        password: root
        url: jdbc:mysql://localhost:3306/imon?createDatabaseIfNotExist=true&useSSL=true
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                id:
                    new_generator_mappings: false
           
    security:
        user:
            name: jay
            password: jay
        basic:
            enabled: false 
    sql:
        init:
            data-locations: classpath:auth.sql 
            
jwt:
    secret: jwtLetYoungEmpowerSecret
    expiry:
        hour: 24
       

server:
   port: 8092 
   
logging:
  level:
    s7:
      application: WARN
    org:
      springframework:
        web: ERROR
    com:
      snipe:
        let: DEBUG
  pattern: 
    file: "%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n"
  file: 
    name : /root/insurancemonster_auth/log/imon_auth.log
       
insurancemonster:
   adminUrl: http://localhost:8091/v1
   authUrl: http://localhost:8092/v1
   locationUrl: http://localhost:8093/v1
   visitsUrl: http://localhost:8094/v1
   employeesUrl: http://localhost:8095/v1
   corporateUrl: http://localhost:8096/v1
   insuranceUrl: http://localhost:8097/v1
   facilitiesUrl: http://localhost:8098/v1
   headerApiKey: IMONEMP
